### ISSUE TITLE
[Proposal] Enhancements for Console configuration

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-cli-plugin-console#149]
## 1. Local config parsing

Currently, the console plugin rd/writes only to the global configuration, for example `aio where` will always show the Org, Project and Workspace selected globally and `aio console project select` will always write to the global configuration.

Instead, if the command is run in an application folder, we could read/write to the local application configuration that is exposed in the .aio and .env files. `@adobe/aio-cli-plugin-events` already takes this approach, see: https://github.com/adobe/aio-cli-plugin-events/blob/master/src/BaseCommand.js#L53

## 2. Align local and global configuration format

There are differences in the global Console configuration and local application configuration format, to avoid bugs and duplicated parsing logic we should realign those two.

To reduce the number of plugins with breaking changes, we should modify the local application configuration format to match the global Console configuration.

## 3. Enhance global configuration

The global Console configuration is missing information such as the service list and credentials information (integrations). If the global and local configuration are realigned, and as as the local config holds all the configuration, we should make sure the global config also sets the full Console configuration.

Also, the Events plugin relies on additional configuration that is fetched from the `console.json` file for the selected workspace. This won't be needed once the global config is enhanced

Secrets can be stored following the current approach: `.env` for local app config and ~`.aio`~ `~/.config/aio` for global configuration secrets.

## 4. Reuse the rd/wr/print Console config logic

The printing and parsing logic is duplicated in every module that interacts with the Console configuration:
- `@adobe/aio-cli-plugin-console`
- `@adobe/aio-cli-plugin-events`
- `@adobe/aio-cli-plugin-auth`
- `@adobe/aio-cli-plugin-app`

Instead of implementing the proposal 4 times, this should be the opportunity to implement the logic in a single dependency, candidates are:
- `@adobe/aio-lib-console`
- create a new `@adobe/aio-lib-cli`
- other ?

**Comment by meryllblanchet** [comment]
@rajarju @Himavanth @purplecabbage @sandeep-paliwal @shazron can you review and provide feedback?

**Comment by rajarju** [comment]
IMO for # 1, 2 and 3 it would be easier if we make a general decision on what goes into global vs local
A simple way to deal with this would be
- Keep all info related to application in the local config
- All developer related config (like authentication/secrets ) should go to global
- We should set the scope local/global when writing rather than reading

for # 4 
- We could have a common base command class which all cli plugins should extend
- I would be an extension of Oclif Command class
- If any plugins, like console, is bringing in some logic that can be reused, It should be exposed separately as a lib

**Comment by Himavanth** [comment]
Agree with `going local`. Local config should always take precedence and override the global config while reading. How about leaving writing to the user with a flag `-g` like npm does with local being the default ?

I think the `reusable parsing logic` for console config should go to `aio-lib-console` because it looks very specific to console config.

**Comment by sarahxxu** [comment]
re: @rajarju 's comment

> IMO for # 1, 2 and 3 it would be easier if we make a general decision on what goes into global vs local
> A simple way to deal with this would be
> 
> - Keep all info related to application in the local config
> - All developer related config (like authentication/secrets ) should go to global
> - We should set the scope local/global when writing rather than reading

I want to clarify the bullets -- to me, "info related to application" = "deploy logic, application name etc"; while "developer related config" = `console.json`. 

Are there any security risk to store things like secrets globally?

**Comment by rajarju** [comment]
> re: @rajarju 's comment
> 
> > IMO for # 1, 2 and 3 it would be easier if we make a general decision on what goes into global vs local
> > A simple way to deal with this would be
> > 
> > - Keep all info related to application in the local config
> > - All developer related config (like authentication/secrets ) should go to global
> > - We should set the scope local/global when writing rather than reading
> 
> I want to clarify the bullets -- to me, "info related to application" = "deploy logic, application name etc"; while "developer related config" = `console.json`. 
> 
> Are there any security risk to store things like secrets globally?

I don't think there is any additional risks of saving secrets under global config. Infact it might be a better practice as it has less chance of getting into the repo

Info related to application, could be config info like org/project/workspace which will be used by cli 

Another way to look would be, which of these conflicts have more chances of being overridden locally. I think secrets have less chances of being overridden for a project locally than Org/project/workspace selection

So by default these will be set locally and if needed devs can set it globally using a flag

**Comment by shazron** [comment]
> 1. Local config parsing 

✅

> 2. Align local and global configuration format

Agree with this, even though it might result in duplication. Or we modify the import of the config to have a different format, is that what you meant?

> 3. Enhance global configuration

❓ Does this mean on import, we import to global as well? I'm not sure this makes sense since service list is context specific for a workspace? My thinking is global is only for global context items like what we have orgid, project, workspace.

> Secrets can be stored following the current approach: .env for local app config and .aio for global configuration secrets.

❓ I think you mean the opposite? `.aio` for config, and `.env` for secrets?

> @rajarju: All developer related config (like authentication/secrets ) should go to global

❓  This doesn't make sense for Runtime credentials for example, which is per workspace (thus shared), and not specific to a developer at all. Which specific ones would you be referring to?

> @rajarju: I don't think there is any additional risks of saving secrets under global config. Infact it might be a better practice as it has less chance of getting into the repo

ℹ️  `.env` is added to .gitignore already when creating a project as well.

> 4. Reuse the rd/wr/print Console config logic 

✅ 

> @Himavanth: I think the reusable parsing logic for console config should go to aio-lib-console because it looks very specific to console config.

⚠️ that is the most logical choice; although it modifies the intent of the library from being an API wrapper to being that plus some other value-added code.

**Comment by rajarju** [comment]
> ❓ This doesn't make sense for Runtime credentials for example, which is per workspace (thus shared), and not specific to a developer at all. Which specific ones would you be referring to? - @shazron 
I thought these credentials were dev specific. Thanks for pointing out.
Even then the only downside would be redundant data in each project config file, won't this be easier to manage than keeping then global, where switching workspace for one project would change it globally, compared to only changing it in the current project.

**Comment by moritzraho** [comment]
sry for the late response:

> ❓ Agree with this, even though it might result in duplication. Or we modify the import of the config to have a different format, is that what you meant?

Yes :) 

> ❓ Does this mean on import, we import to global as well? I'm not sure this makes sense since service list is context specific for a workspace? My thinking is global is only for global context items like what we have orgid, project, workspace

Yes that was my intent. As we are anyways selecting an org, project and workspace globally, we might as well fetch all the data attached to the workspace. Plugins might need more config to be set globally, for example the events plugin is relying on the credentials JWT client id which is not part of the global console config yet (current workaround is to download the console file from the events plugin and store the client id into a global `event` config)

> ❓ I think you mean the opposite? .aio for config, and .env for secrets?

Sorry I did a mistake, I meant: `.env` for local app secrets, `.aio` for local config and `~/.config/aio` for storing both global config and secrets like global console config and `cli` login tokens

**Comment by kptdobe** [comment]
If I may give you my "user" point: today it is really confusing and error prone that the console configuration is global. I managed to override one of my production app because I thought I was in the staging workspace (which I did not know I was only changing globally - thus no impact on my app). I think this is definitively something to change and I am happy you are considering it!

I wanted to open a ticket to describe that the secret management is a pain:  when you want to switch workspace, you have to first find the credentials somewhere (not so obvious that you have to download the workspace config) and then know which file - `.env` or `console.json` or `.aio` - to update. This requires that as a user you know a lot of internals. But I assume (well, I hope) that the switch workspace that will derive from this initiative will solve this problem and make the switch fully natural for a non expert developer.

**Comment by meryllblanchet** [comment]
Hi @kptdobe  and thanks for sharing. This is definitely a part that we're aiming to improve based on users feedback. 
Just to confirm: have you used the following flow?

`1. Enter your application source code folder`
cd yourproject/ 

`2. Check your currently selected working org/project/workspace combo, globally defined`
aio where

`list and change your org, if needed`
aio org list
aio org select xxx

`list and change your project, if needed`
aio console project list
aio console project select yyy

`list and change your workspace, if needed`
aio console workspace list
aio console workspace select zzz

`download the config file for the selected combo and generate the .env and .aio in your current folder`
aio app use

**Comment by kptdobe** [comment]
I stopped after `aio console workspace select zzz` since I assumed it is applied locally.

Where you I `download the config file for the selected combo` ? If this is in the console, then all the steps before would be useless.

There are 2 distincts flows here: 
1. all first steps: change org / project / workspace globally
2. download a config to apply it locally

You can admit that this is not really obvious ;)

**Comment by meryllblanchet** [comment]
You can either download the config file from the Console UI, which makes the CLI flow redundant, or follow the steps that I described above, within your project folder.

In that case, `aio app use` will ask you to confirm that you want to use the currently selected combo, after what it will download the workspace configuration and generate the corresponding .env and .aio.

You can also do the same with an intermediate step:

aio console workspace download

`With this intermediate step, you'll have to specify the name/path of the json file`
aio app use downloadedfile.json

Indeed, this whole flow needs to be added to the Project Firefly documentation. I opened this [issue](https://github.com/AdobeDocs/project-firefly/issues/51) accordingly.

**Comment by kptdobe** [comment]
ah ok, got it now. Not trivial. But it seems that issue will simplify this process.

**Comment by moritzraho** [comment]
closing in favor of https://github.com/adobe/aio-cli/issues/256
